// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";

/**
 * AppConfig 应用配置结构体
 */
export class AppConfig {
    "access_token"?: string;
    "bangumi_refresh_token"?: string;
    "bangumi_token_expires_at"?: string;
    "bangumi_authorized_user_id"?: string;
    "bangumi_authorized_username"?: string;
    "bangumi_authorized_avatar_url"?: string;
    "bangumi_auth_error"?: string;
    "bangumi_status_push_enabled"?: boolean | null;
    "hikarinagi_access_token"?: string;
    "hikarinagi_refresh_token"?: string;
    "hikarinagi_token_expires_at"?: string;
    "hikarinagi_authorized_user_id"?: string;
    "hikarinagi_authorized_username"?: string;
    "hikarinagi_authorized_avatar_url"?: string;
    "hikarinagi_auth_error"?: string;
    "hikarinagi_status_push_enabled"?: boolean | null;
    "nextmoe_access_token"?: string;
    "nextmoe_refresh_token"?: string;
    "nextmoe_token_expires_at"?: string;
    "nextmoe_account_label"?: string;
    "vndb_access_token"?: string;

    /**
     * 元数据拉取来源列表（vndb/bangumi/bangumi_mirror/ymgal/hikarinagi/nextmoe）
     */
    "metadata_sources"?: string[];

    /**
     * CurrentMetadataSource 是「当前资料源」：游戏资料优先展示/抓取哪个来源。
     * 对齐手机版设置里的「右侧资料源」（`metadata_source`）。单个取值，
     * 与上面「启用了哪些来源」的多选相互独立。
     */
    "current_metadata_source"?: enums$0.SourceType;

    /**
     * 批量/外部导入时允许相同 source_type + source_id
     */
    "allow_duplicate_metadata_import": boolean;

    /**
     * Bangumi 封面来源
     */
    "bangumi_cover_source"?: enums$0.MetadataCoverSource;

    /**
     * VNDB 封面来源
     */
    "vndb_cover_source"?: enums$0.MetadataCoverSource;

    /**
     * light or dark
     */
    "theme": string;

    /**
     * zh, en, etc.
     */
    "language": string;

    /**
     * 侧边栏是否展开
     */
    "sidebar_open": boolean;

    /**
     * 关闭时最小化到托盘
     */
    "close_to_tray": boolean;

    /**
     * AI 配置
     * openai, deepseek, etc.
     */
    "ai_provider"?: string;

    /**
     * API base URL
     */
    "ai_base_url"?: string;

    /**
     * API key
     */
    "ai_api_key"?: string;

    /**
     * model name
     */
    "ai_model"?: string;

    /**
     * AI 系统提示语
     */
    "ai_system_prompt"?: string;

    /**
     * AI 高级配置（防剧透 / WebSearch / 上下文）
     * none | mild | full，全局防剧透默认等级
     */
    "ai_spoiler_level"?: string;

    /**
     * 是否启用 WebSearch 工具调用
     */
    "ai_web_search": boolean;

    /**
     * 送入的历史 session 数量上限（0=默认10）
     */
    "ai_context_window"?: number;

    /**
     * Tavily Search API Key（WebSearch）
     */
    "tavily_api_key"?: string;

    /**
     * 是否启用 GUI 内嵌 MCP HTTP 服务
     */
    "mcp_enabled": boolean;

    /**
     * MCP HTTP 服务监听端口（仅绑定 127.0.0.1）
     */
    "mcp_port"?: number;

    /**
     * 云备份配置
     * 是否启用云备份
     */
    "cloud_backup_enabled": boolean;

    /**
     * 云备份提供商: s3, onedrive, umbra, webdav
     */
    "cloud_backup_provider"?: string;

    /**
     * 备份密码（用于生成 user-id 和加密）
     */
    "backup_password"?: string;

    /**
     * 云端用户标识（由备份密码 hash 生成）
     */
    "backup_user_id"?: string;

    /**
     * 是否启用云同步
     */
    "cloud_sync_enabled": boolean;

    /**
     * 是否启用自动云同步（启动时 + 定时）
     */
    "auto_cloud_sync_enabled": boolean;

    /**
     * 定时全量同步间隔（秒）
     */
    "cloud_sync_interval_sec": number;

    /**
     * 上次云同步时间
     */
    "last_cloud_sync_time"?: string;

    /**
     * 上次云同步状态: idle/syncing/success/failed
     */
    "last_cloud_sync_status"?: string;

    /**
     * 上次云同步错误
     */
    "last_cloud_sync_error"?: string;

    /**
     * S3 兼容端点
     */
    "s3_endpoint"?: string;

    /**
     * S3 区域
     */
    "s3_region"?: string;

    /**
     * S3 存储桶
     */
    "s3_bucket"?: string;

    /**
     * S3 Access Key
     */
    "s3_access_key"?: string;

    /**
     * S3 Secret Key
     */
    "s3_secret_key"?: string;

    /**
     * 云端每个游戏保留的存档备份数量
     */
    "cloud_backup_retention"?: number;

    /**
     * 云端保留的数据库备份数量
     */
    "cloud_db_backup_retention"?: number;

    /**
     * YukiHub 账号（自建账号服务 yukihub.zh.kg）
     * 
     * 令牌与第三方授权一样明文存在 appconf.json（与 Bangumi 个人令牌同一处理方式），
     * 桌面端没有更可靠的本地密钥存储可用。
     */
    "yukihub_account_access_token"?: string;
    "yukihub_account_refresh_token"?: string;
    "yukihub_account_user_id"?: string;
    "yukihub_account_uid"?: number;
    "yukihub_account_nickname"?: string;
    "yukihub_account_email"?: string;
    "yukihub_account_avatar"?: string;
    "yukihub_account_kungal_bound"?: boolean;
    "yukihub_account_hikarinagi_bound"?: boolean;

    /**
     * YukiHubAccountCloudSyncEnabled 控制「登录后自动同步游戏库」。
     */
    "yukihub_account_cloud_sync_enabled": boolean;

    /**
     * YukiHubAccountSharePlaying 为 false 时仍然上报心跳，但不带上「正在玩」。
     */
    "yukihub_account_share_playing": boolean;

    /**
     * YukiHubAccountFriendPlayNotify 控制「好友开始玩游戏时弹通知」。
     * 
     * 与手机版 PresenceManager.KEY_FRIEND_PLAY_NOTIFY 同义，默认开。
     * 用指针是为了区分「配置里没有这个字段」（nil，按默认开）和「用户主动
     * 关掉」（false）—— 普通 bool 的零值会把「老配置里没这个字段」误判成
     * 「用户关了通知」，于是新功能在已登录用户那里静默失效。
     */
    "yukihub_account_friend_play_notify"?: boolean | null;

    /**
     * LastYukiHubAccountSyncHash 是上次同步的快照哈希，用于判断两边有没有改动。
     */
    "last_yukihub_account_sync_hash"?: string;
    "last_yukihub_account_sync_at"?: string;

    /**
     * OneDrive OAuth 配置
     * OneDrive Client ID
     */
    "onedrive_client_id"?: string;

    /**
     * OneDrive Refresh Token（OAuth 授权后获得）
     */
    "onedrive_refresh_token"?: string;

    /**
     * WebDAV 配置（游戏存档 / 数据库备份用的云存储）
     * WebDAV 服务地址（可含子路径）
     */
    "webdav_url"?: string;

    /**
     * WebDAV 用户名
     */
    "webdav_username"?: string;

    /**
     * WebDAV 密码
     */
    "webdav_password"?: string;

    /**
     * 自持同步（WebDAV）：把与手机版**完全相同**的 schema 5 快照同步到用户自己的
     * WebDAV 网盘，对应手机版 SyncManager 的 `sync()`（云端文件 YukiHub/YukiHub_sync.json）。
     * 
     * 与上面那组 WebDAV 配置是两回事：那组是「游戏存档备份」的云存储后端（LunaBox 血统），
     * 这组是「游戏库整体同步」的传输通道（手机版血统）。两者互不影响，可以只配一个。
     * 密码同样明文存 appconf.json —— 与手机版存 SharedPreferences、以及本文件其它凭据一致。
     * WebDAV 服务地址
     */
    "self_sync_url"?: string;

    /**
     * WebDAV 用户名
     */
    "self_sync_username"?: string;

    /**
     * WebDAV 密码 / 应用密码
     */
    "self_sync_password"?: string;

    /**
     * SelfSyncAutoSync 对应手机版的「自动同步」开关（启动时同步一次）。
     */
    "self_sync_auto_sync": boolean;

    /**
     * SelfSyncLastHash 是上次同步时本地快照的哈希，用于判断两边有没有改动。
     */
    "self_sync_last_hash"?: string;
    "self_sync_last_at"?: string;

    /**
     * Umbra OAuth 配置（token 与设备密钥由 DPAPI 加密存储，不写入配置文件）
     * Umbra 服务地址
     */
    "umbra_base_url"?: string;

    /**
     * 是否已完成 OAuth 与设备注册
     */
    "umbra_authenticated"?: boolean;

    /**
     * 数据库备份
     * 上次数据库备份时间
     */
    "last_db_backup_time"?: string;

    /**
     * 待恢复的数据库备份路径（重启后执行）
     */
    "pending_db_restore"?: string;

    /**
     * 上次全量数据备份时间
     */
    "last_full_backup_time"?: string;

    /**
     * 待恢复的全量数据备份路径（重启后执行）
     */
    "pending_full_restore"?: string;

    /**
     * 自动备份配置
     * 退出时自动备份数据库
     */
    "auto_backup_db": boolean;

    /**
     * 游戏退出时自动备份存档
     */
    "auto_backup_game_save": boolean;

    /**
     * 自动上传数据库备份到云端
     */
    "auto_upload_db_to_cloud": boolean;

    /**
     * 自动上传游戏存档备份到云端
     */
    "auto_upload_game_save_to_cloud": boolean;

    /**
     * 启动游戏前自动恢复较新的云端存档
     */
    "auto_restore_cloud_save_before_launch": boolean;

    /**
     * 是否启用定时数据库备份
     */
    "scheduled_db_backup_enabled": boolean;

    /**
     * interval / daily
     */
    "scheduled_db_backup_mode"?: string;

    /**
     * 固定间隔分钟数
     */
    "scheduled_db_backup_interval_minutes": number;

    /**
     * 每日备份时间 HH:mm
     */
    "scheduled_db_backup_time"?: string;

    /**
     * 备份保留策略
     * 本地游戏备份保留数量
     */
    "local_backup_retention": number;

    /**
     * 本地数据库备份保留数量
     */
    "local_db_backup_retention": number;

    /**
     * 窗口尺寸记忆
     * 窗口宽度
     */
    "window_width": number;

    /**
     * 窗口高度
     */
    "window_height": number;

    /**
     * 窗口是否最大化
     */
    "window_maximised": boolean;

    /**
     * 应用界面缩放倍率
     */
    "window_zoom_factor": number;

    /**
     * Windows 登录后自动启动应用
     */
    "launch_at_login": boolean;

    /**
     * 活跃时间追踪配置
     * 仅记录活跃游玩时长（窗口在前台时）
     */
    "record_active_time_only": boolean;

    /**
     * 游戏窗口进入后台时静音
     */
    "mute_game_in_background": boolean;

    /**
     * 启动后检测实际游戏进程的最长等待时间
     */
    "process_detection_timeout_sec": number;

    /**
     * PlayTimingMode 是全局计时模式：process（进程监测，默认）/ manual（手动计时）。
     * 空串（老配置里没有这个字段）按默认处理，见 NormalizePlayTimingMode。
     */
    "play_timing_mode"?: string;

    /**
     * 自动更新配置
     * 启动时自动检查更新
     */
    "check_update_on_startup": boolean;

    /**
     * 更新源：gitcode（默认）/ github
     */
    "update_source"?: string;

    /**
     * 自定义更新检查 URL
     */
    "update_check_url"?: string;

    /**
     * 上次更新检查时间
     */
    "last_update_check"?: string;

    /**
     * 跳过的版本号（用户选择忽略的更新）
     */
    "skip_version"?: string;

    /**
     * 背景图配置
     * 自定义背景图路径
     */
    "background_image"?: string;

    /**
     * 背景模糊度 (0-20)
     */
    "background_blur": number;

    /**
     * 背景不透明度 (0-1)
     */
    "background_opacity": number;

    /**
     * 是否启用自定义背景
     */
    "background_enabled": boolean;

    /**
     * 启用自定义背景时隐藏首页游戏封面
     */
    "background_hide_game_cover": boolean;

    /**
     * 启用自定义背景时隐藏首页游戏封面大图
     */
    "background_hide_game_hero_cover": boolean;

    /**
     * 记录自定义背景是不是浅色调
     */
    "background_is_light": boolean;

    /**
     * 首页游戏封面是否自动轮播
     */
    "home_game_carousel_enabled": boolean;

    /**
     * 首页游戏封面轮播间隔（秒）
     */
    "home_game_carousel_interval_sec": number;

    /**
     * Locale Emulator 和 Magpie 配置
     * Locale Emulator 可执行文件路径
     */
    "locale_emulator_path"?: string;

    /**
     * Magpie 可执行文件路径
     */
    "magpie_path"?: string;

    /**
     * 新添加的游戏默认启用 Locale Emulator
     */
    "default_use_locale_emulator": boolean;

    /**
     * 新添加的游戏默认启用 Magpie
     */
    "default_use_magpie": boolean;

    /**
     * Linux Wine 可执行文件路径
     */
    "wine_runner_path"?: string;

    /**
     * Linux 默认 WINEPREFIX 或 Proton prefix
     */
    "wine_prefix"?: string;

    /**
     * Linux winetricks 可执行文件路径
     */
    "winetricks_path"?: string;

    /**
     * Linux protontricks 可执行文件路径
     */
    "protontricks_path"?: string;

    /**
     * 历史字段：CrossOver bundle 内的 wine 可执行文件路径
     */
    "crossover_runner_path"?: string;

    /**
     * 历史字段：CrossOver bottle 名
     */
    "crossover_bottle"?: string;

    /**
     * 时区配置
     * 数据库使用的 IANA 时区名称（如 "Asia/Shanghai"）
     */
    "time_zone"?: string;

    /**
     * 游戏库路径配置
     * 游戏库主目录（下载的游戏将解压到此）
     */
    "game_library_path"?: string;

    /**
     * 批量导入偏好
     * 批量导入扫描预设
     */
    "batch_import_scan_preset"?: string;

    /**
     * 批量导入按目录导入层级
     */
    "batch_import_hierarchy_depth": number;
    "batch_import_preferred_source"?: string;

    /**
     * 批量导入目录选择器上次打开的目录
     */
    "batch_import_last_directory"?: string;

    /**
     * 网络代理配置
     * 全局网络代理模式：system / manual / direct
     */
    "network_proxy_mode"?: string;

    /**
     * 全局手动代理 URL
     */
    "network_proxy_url"?: string;

    /**
     * Tag 配置
     * 是否在详情页展示 NSFW tag，默认 false
     */
    "show_nsfw_tags": boolean;

    /**
     * 是否显示 VNDB tag 中文翻译，默认 true
     */
    "enable_tag_translation": boolean;

    /**
     * 刮削 tag 数量上限，-1 表示不限制，0 表示不刮削 tag
     */
    "scraped_tag_limit": number;

    /**
     * 游戏卡片显示
     * 游戏库卡片布局：portrait / landscape
     */
    "game_card_layout"?: string;

    /**
     * 是否在游戏卡片封面底部展示当前排序字段对应的值
     */
    "show_sort_field_on_cover": boolean;

    /**
     * 是否模糊 NSFW 游戏封面
     */
    "blur_nsfw_game_covers": boolean;

    /**
     * 大屏模式配置（对齐手机端 BigScreenPrefs 的 bigscreen_* 键）
     * 大屏模式是否展示已隐藏的游戏，默认 false
     */
    "bigscreen_show_hidden_game": boolean;

    /**
     * 大屏模式默认分类，默认 recent
     */
    "bigscreen_default_category"?: string;

    /**
     * 大屏氛围特效档位：off / low / high，默认 low
     */
    "bigscreen_effect_level"?: string;

    /**
     * 大屏界面音效开关，默认 true
     */
    "bigscreen_sound_enabled": boolean;

    /**
     * 大屏界面音效音量（0-100），默认 65
     */
    "bigscreen_sound_volume": number;

    /**
     * 焦点移动音，默认 true
     */
    "bigscreen_focus_ticks": boolean;

    /**
     * 入场动画，默认 true
     */
    "bigscreen_intro_enabled": boolean;

    /**
     * 自选入场视频（/local/intro/...）；空 = 内置动画（对齐手机端 M18-2）
     */
    "bigscreen_intro_video"?: string;

    /**
     * 卡片上再显示游戏名（默认 false，名字已在信息浮层）
     */
    "bigscreen_show_titles": boolean;

    /**
     * 卡片大小倍率（×100），默认 112
     */
    "bigscreen_card_scale": number;

    /**
     * 焦点缩放幅度（%），0 表示只描边，默认 100
     */
    "bigscreen_focus_scale": number;

    /**
     * 按键图标风格：xbox / ps，默认 xbox
     */
    "bigscreen_key_style"?: string;

    /**
     * 按键提示条：auto（4s 后淡出）/ always / off，默认 auto
     */
    "bigscreen_hint_mode"?: string;

    /**
     * 侧栏钉住展开，默认 false
     */
    "bigscreen_rail_expanded": boolean;

    /**
     * 背景预告片总开关，默认 true
     */
    "bigscreen_trailer_enabled": boolean;

    /**
     * 预告片静音，默认 false
     */
    "bigscreen_trailer_muted": boolean;

    /**
     * 焦点停留多久后起播预告片（毫秒），默认 2000
     */
    "bigscreen_trailer_delay_ms": number;

    /**
     * 预告片显示方式：false=铺满裁切 / true=原比例留黑边，默认 false
     */
    "bigscreen_pv_fit": boolean;

    /**
     * 预告片遮罩，默认 true
     */
    "bigscreen_pv_scrim": boolean;

    /**
     * 预告片遮罩强度（0-100），默认 45
     */
    "bigscreen_pv_scrim_percent": number;

    /**
     * 顶部提示条停留时长（毫秒），默认 2000
     */
    "bigscreen_banner_hold_ms": number;

    /**
     * 背景氛围层（雪花 / 极光），默认 true
     */
    "bigscreen_snow_enabled": boolean;

    /**
     * 只在详情层播放预告片（对齐手机端 bigscreen_trailer_details_only，中性能档默认行为）
     */
    "bigscreen_trailer_details_only": boolean;

    /**
     * 记住上次的分类筛选，默认 true
     */
    "bigscreen_remember_filter": boolean;

    /**
     * 上次停留的分类（仅在记住筛选打开时写入）
     */
    "bigscreen_last_category"?: string;

    /**
     * OverlayShortcut 是「呼出游戏内好友栏」的全局快捷键，accelerator 形式
     * （如 "shift+`"）。空字符串表示用默认值（service.DefaultOverlayShortcut）；
     * 界面展示成 “Shift + ~”，转换在 service.FormatOverlayShortcut。
     */
    "overlay_shortcut"?: string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("allow_duplicate_metadata_import" in $$source)) {
            this["allow_duplicate_metadata_import"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("sidebar_open" in $$source)) {
            this["sidebar_open"] = false;
        }
        if (!("close_to_tray" in $$source)) {
            this["close_to_tray"] = false;
        }
        if (!("ai_web_search" in $$source)) {
            this["ai_web_search"] = false;
        }
        if (!("mcp_enabled" in $$source)) {
            this["mcp_enabled"] = false;
        }
        if (!("cloud_backup_enabled" in $$source)) {
            this["cloud_backup_enabled"] = false;
        }
        if (!("cloud_sync_enabled" in $$source)) {
            this["cloud_sync_enabled"] = false;
        }
        if (!("auto_cloud_sync_enabled" in $$source)) {
            this["auto_cloud_sync_enabled"] = false;
        }
        if (!("cloud_sync_interval_sec" in $$source)) {
            this["cloud_sync_interval_sec"] = 0;
        }
        if (!("yukihub_account_cloud_sync_enabled" in $$source)) {
            this["yukihub_account_cloud_sync_enabled"] = false;
        }
        if (!("yukihub_account_share_playing" in $$source)) {
            this["yukihub_account_share_playing"] = false;
        }
        if (!("self_sync_auto_sync" in $$source)) {
            this["self_sync_auto_sync"] = false;
        }
        if (!("auto_backup_db" in $$source)) {
            this["auto_backup_db"] = false;
        }
        if (!("auto_backup_game_save" in $$source)) {
            this["auto_backup_game_save"] = false;
        }
        if (!("auto_upload_db_to_cloud" in $$source)) {
            this["auto_upload_db_to_cloud"] = false;
        }
        if (!("auto_upload_game_save_to_cloud" in $$source)) {
            this["auto_upload_game_save_to_cloud"] = false;
        }
        if (!("auto_restore_cloud_save_before_launch" in $$source)) {
            this["auto_restore_cloud_save_before_launch"] = false;
        }
        if (!("scheduled_db_backup_enabled" in $$source)) {
            this["scheduled_db_backup_enabled"] = false;
        }
        if (!("scheduled_db_backup_interval_minutes" in $$source)) {
            this["scheduled_db_backup_interval_minutes"] = 0;
        }
        if (!("local_backup_retention" in $$source)) {
            this["local_backup_retention"] = 0;
        }
        if (!("local_db_backup_retention" in $$source)) {
            this["local_db_backup_retention"] = 0;
        }
        if (!("window_width" in $$source)) {
            this["window_width"] = 0;
        }
        if (!("window_height" in $$source)) {
            this["window_height"] = 0;
        }
        if (!("window_maximised" in $$source)) {
            this["window_maximised"] = false;
        }
        if (!("window_zoom_factor" in $$source)) {
            this["window_zoom_factor"] = 0;
        }
        if (!("launch_at_login" in $$source)) {
            this["launch_at_login"] = false;
        }
        if (!("record_active_time_only" in $$source)) {
            this["record_active_time_only"] = false;
        }
        if (!("mute_game_in_background" in $$source)) {
            this["mute_game_in_background"] = false;
        }
        if (!("process_detection_timeout_sec" in $$source)) {
            this["process_detection_timeout_sec"] = 0;
        }
        if (!("check_update_on_startup" in $$source)) {
            this["check_update_on_startup"] = false;
        }
        if (!("background_blur" in $$source)) {
            this["background_blur"] = 0;
        }
        if (!("background_opacity" in $$source)) {
            this["background_opacity"] = 0;
        }
        if (!("background_enabled" in $$source)) {
            this["background_enabled"] = false;
        }
        if (!("background_hide_game_cover" in $$source)) {
            this["background_hide_game_cover"] = false;
        }
        if (!("background_hide_game_hero_cover" in $$source)) {
            this["background_hide_game_hero_cover"] = false;
        }
        if (!("background_is_light" in $$source)) {
            this["background_is_light"] = false;
        }
        if (!("home_game_carousel_enabled" in $$source)) {
            this["home_game_carousel_enabled"] = false;
        }
        if (!("home_game_carousel_interval_sec" in $$source)) {
            this["home_game_carousel_interval_sec"] = 0;
        }
        if (!("default_use_locale_emulator" in $$source)) {
            this["default_use_locale_emulator"] = false;
        }
        if (!("default_use_magpie" in $$source)) {
            this["default_use_magpie"] = false;
        }
        if (!("batch_import_hierarchy_depth" in $$source)) {
            this["batch_import_hierarchy_depth"] = 0;
        }
        if (!("show_nsfw_tags" in $$source)) {
            this["show_nsfw_tags"] = false;
        }
        if (!("enable_tag_translation" in $$source)) {
            this["enable_tag_translation"] = false;
        }
        if (!("scraped_tag_limit" in $$source)) {
            this["scraped_tag_limit"] = 0;
        }
        if (!("show_sort_field_on_cover" in $$source)) {
            this["show_sort_field_on_cover"] = false;
        }
        if (!("blur_nsfw_game_covers" in $$source)) {
            this["blur_nsfw_game_covers"] = false;
        }
        if (!("bigscreen_show_hidden_game" in $$source)) {
            this["bigscreen_show_hidden_game"] = false;
        }
        if (!("bigscreen_sound_enabled" in $$source)) {
            this["bigscreen_sound_enabled"] = false;
        }
        if (!("bigscreen_sound_volume" in $$source)) {
            this["bigscreen_sound_volume"] = 0;
        }
        if (!("bigscreen_focus_ticks" in $$source)) {
            this["bigscreen_focus_ticks"] = false;
        }
        if (!("bigscreen_intro_enabled" in $$source)) {
            this["bigscreen_intro_enabled"] = false;
        }
        if (!("bigscreen_show_titles" in $$source)) {
            this["bigscreen_show_titles"] = false;
        }
        if (!("bigscreen_card_scale" in $$source)) {
            this["bigscreen_card_scale"] = 0;
        }
        if (!("bigscreen_focus_scale" in $$source)) {
            this["bigscreen_focus_scale"] = 0;
        }
        if (!("bigscreen_rail_expanded" in $$source)) {
            this["bigscreen_rail_expanded"] = false;
        }
        if (!("bigscreen_trailer_enabled" in $$source)) {
            this["bigscreen_trailer_enabled"] = false;
        }
        if (!("bigscreen_trailer_muted" in $$source)) {
            this["bigscreen_trailer_muted"] = false;
        }
        if (!("bigscreen_trailer_delay_ms" in $$source)) {
            this["bigscreen_trailer_delay_ms"] = 0;
        }
        if (!("bigscreen_pv_fit" in $$source)) {
            this["bigscreen_pv_fit"] = false;
        }
        if (!("bigscreen_pv_scrim" in $$source)) {
            this["bigscreen_pv_scrim"] = false;
        }
        if (!("bigscreen_pv_scrim_percent" in $$source)) {
            this["bigscreen_pv_scrim_percent"] = 0;
        }
        if (!("bigscreen_banner_hold_ms" in $$source)) {
            this["bigscreen_banner_hold_ms"] = 0;
        }
        if (!("bigscreen_snow_enabled" in $$source)) {
            this["bigscreen_snow_enabled"] = false;
        }
        if (!("bigscreen_trailer_details_only" in $$source)) {
            this["bigscreen_trailer_details_only"] = false;
        }
        if (!("bigscreen_remember_filter" in $$source)) {
            this["bigscreen_remember_filter"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField21_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata_sources" in $$parsedSource) {
            $$parsedSource["metadata_sources"] = $$createField21_0($$parsedSource["metadata_sources"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
