// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService 是 YukiHub 自建账号（yukihub.zh.kg）在桌面端的入口：
 * 登录 / 注册 / 资料、云同步游戏库、在线状态，以及好友与聊天。
 * 
 * 登录与云同步之所以放在同一个服务里：它们共用一份访问令牌，
 * 而令牌的刷新要集中处理（多处各自刷新会互相顶掉）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as yukihubaccount$0 from "./yukihubaccount/models.js";

/**
 * AcceptFriendRequest 接受好友申请。
 * 
 * friendshipID 是**数字**（服务端下发与回传都是数字）；只拿得到对方 uid 的场景
 * （资料页）传 0 + uid。
 */
export function AcceptFriendRequest(friendshipID: number, uid: number): $CancellablePromise<void> {
    return $Call.ByID(180565005, friendshipID, uid);
}

/**
 * CloseNativeNotifier 移除系统通知用的隐藏托盘图标。
 * 
 * 应用退出时必须调用：不显式移除的话 Windows 会在托盘区留下「幽灵图标」，
 * 直到鼠标划过那一小块才会消失。
 */
export function CloseNativeNotifier(): $CancellablePromise<void> {
    return $Call.ByID(2011224681);
}

/**
 * GetAccountLevel 查询等级 / 经验 / 签到状态。
 */
export function GetAccountLevel(): $CancellablePromise<vo$0.AccountLevel> {
    return $Call.ByID(81280639).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAccountStatus 返回当前账号状态（不含令牌）。
 */
export function GetAccountStatus(): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(1825179945).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetChatHistory 拉与某人的历史消息。
 */
export function GetChatHistory(friendID: string, offset: number, limit: number): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(1025797374, friendID, offset, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetChatUnreadCount 未读消息总数。
 */
export function GetChatUnreadCount(): $CancellablePromise<number> {
    return $Call.ByID(2745218308);
}

/**
 * GetGroupHistory 群历史消息。
 */
export function GetGroupHistory(groupID: string, offset: number, limit: number): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(1169809469, groupID, offset, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGroupOnlineCount 群聊当前在线人数。
 * 
 * 服务端把它挂在群历史接口的响应里（与手机版 getGroupMessages 的 onlineCount
 * 同一来源），所以这里拉 1 条消息顺带取人数——标题栏「🟢N在线」用。
 */
export function GetGroupOnlineCount(groupID: string): $CancellablePromise<number> {
    return $Call.ByID(1592541707, groupID);
}

/**
 * GetUserProfile 拉取某个 UID 的用户资料（友链列表、群聊点头像进资料页）。
 */
export function GetUserProfile(uid: number): $CancellablePromise<yukihubaccount$0.UserProfile> {
    return $Call.ByID(1868535084, uid).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListChatEmojis 本站表情列表。
 */
export function ListChatEmojis(): $CancellablePromise<yukihubaccount$0.ChatEmoji[]> {
    return $Call.ByID(4088162309).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListChatGroups 群列表。
 */
export function ListChatGroups(): $CancellablePromise<yukihubaccount$0.ChatGroup[]> {
    return $Call.ByID(2834922682).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListChatStickerPacks 拉未萌贴纸包列表（服务端代理）。
 * Enabled=false 表示服务端未启用，界面隐藏「未萌贴纸」入口。
 */
export function ListChatStickerPacks(): $CancellablePromise<vo$0.ChatStickerList> {
    return $Call.ByID(3198305305).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListChatStickerURLs 拉某个未萌贴纸包里的全部表情地址。
 */
export function ListChatStickerURLs(packID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3022118279, packID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListFriendRequests 好友申请列表（收到的 + 已发出的）。
 * 
 * 与 ListFriends 分开：列表接口里的 `pendingRequests` 只是个**数字**，
 * 申请内容要单独拉 `/friends/requests`（手机版 SocialApiClient.getFriendRequests）。
 */
export function ListFriendRequests(): $CancellablePromise<yukihubaccount$0.FriendRequests> {
    return $Call.ByID(1858416362).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListFriends 好友列表与待处理申请数。
 */
export function ListFriends(): $CancellablePromise<yukihubaccount$0.FriendList> {
    return $Call.ByID(138003445).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * LoginAccount 用邮箱 + 密码登录。
 */
export function LoginAccount(email: string, password: string): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(3439494088, email, password).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LogoutAccount 退出登录：清本地会话、停心跳、尽力通知服务端下线。
 */
export function LogoutAccount(): $CancellablePromise<void> {
    return $Call.ByID(1118106453);
}

/**
 * ManageGroupMessage 撤回或删除群消息（仅管理员，服务端会校验权限）。
 * 
 * action 取 "recall"（撤回）或 "delete"（删除），与手机版 doManageGroupMessage 一致。
 */
export function ManageGroupMessage(messageID: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(1170371849, messageID, action);
}

/**
 * NotifyOffline 尽力上报一次下线（**关闭客户端**时调用，退出登录走 LogoutAccount）。
 * 
 * 契约（docs/yukihub-presence-platform.md §3.3）要求「退出登录 / 关闭客户端时
 * 尽力调用一次」：调不通也没关系，服务端 10 分钟收不到心跳会自动判离线。
 * 失败只记日志，绝不阻塞退出流程；调用方负责限时。
 * 
 * 会**先停掉心跳循环**再上报：否则一个刚好到点的 tick 会把状态又顶回在线，
 * 好友那边要再过 10 分钟才看到你离开。
 */
export function NotifyOffline(): $CancellablePromise<void> {
    return $Call.ByID(4229925392);
}

/**
 * PollChatMessages 拉新消息（前端每 10 秒调一次，与手机版一致）。
 */
export function PollChatMessages(afterID: string, friendID: string, peek: boolean): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(3275711423, afterID, friendID, peek).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PollGroupMessages 拉群新消息。
 */
export function PollGroupMessages(groupID: string, afterID: string): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(3718523948, groupID, afterID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RegisterAccount 用邮箱 + 验证码注册并直接进入登录状态。
 */
export function RegisterAccount(email: string, password: string, nickname: string, code: string): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(586367668, email, password, nickname, code).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RejectFriendRequest 拒绝好友申请。
 */
export function RejectFriendRequest(friendshipID: number): $CancellablePromise<void> {
    return $Call.ByID(282440252, friendshipID);
}

/**
 * RemoveFriend 删除好友。
 */
export function RemoveFriend(friendID: string): $CancellablePromise<void> {
    return $Call.ByID(2457191756, friendID);
}

/**
 * ReportChatMessage 举报一条聊天消息。
 * 
 * scene = "chat"（私聊）/ "group"（群聊），群聊时 groupID 必填。
 */
export function ReportChatMessage(scene: string, messageID: string, groupID: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(2560409231, scene, messageID, groupID, reason);
}

/**
 * ResetAccountPassword 用邮箱验证码重置密码。
 */
export function ResetAccountPassword(email: string, code: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3688801563, email, code, password);
}

/**
 * SearchUsers 搜用户。
 */
export function SearchUsers(keyword: string): $CancellablePromise<yukihubaccount$0.Friend[]> {
    return $Call.ByID(865387128, keyword).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SelectChatImage 打开图片选择对话框，选中后读取文件内容（供聊天图片消息用）。
 * 
 * 返回 (路径, 内容字节, MIME 类型)；用户取消时路径为空串、其余为零值。
 * 压缩在浏览器侧做不了、后端再做一遍太绕：服务端上限 500KB，这里只校验大小
 * 并按扩展名给出 MIME，超限时直接报错提示用户换图（与手机版行为一致）。
 */
export function SelectChatImage(): $CancellablePromise<vo$0.ChatImagePick> {
    return $Call.ByID(917861247).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SendAccountCode 发送邮箱验证码。purpose 传 "register"（默认）或 "reset"。
 */
export function SendAccountCode(email: string, purpose: string): $CancellablePromise<void> {
    return $Call.ByID(3958706468, email, purpose);
}

/**
 * SendChatMessage 发私聊消息。
 */
export function SendChatMessage(receiverID: string, content: string, msgType: string, replyToID: string): $CancellablePromise<yukihubaccount$0.ChatMessage> {
    return $Call.ByID(2333574947, receiverID, content, msgType, replyToID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SendFriendRequest 发好友申请。
 */
export function SendFriendRequest(target: string): $CancellablePromise<void> {
    return $Call.ByID(2174757163, target);
}

/**
 * SendGroupMessage 发群消息。
 */
export function SendGroupMessage(groupID: string, content: string, msgType: string, replyToID: string): $CancellablePromise<yukihubaccount$0.ChatMessage> {
    return $Call.ByID(2435495340, groupID, content, msgType, replyToID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetAccountCloudSyncEnabled 开关「登录后自动同步」。
 */
export function SetAccountCloudSyncEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3584650856, enabled);
}

/**
 * SetAccountFriendPlayNotify 开关「好友开始玩游戏时通知」。
 */
export function SetAccountFriendPlayNotify(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3499901004, enabled);
}

/**
 * SetAccountSharePlaying 开关「向好友展示正在玩的游戏」。
 */
export function SetAccountSharePlaying(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1073884660, enabled);
}

/**
 * SetFriendNote 设置好友备注。
 */
export function SetFriendNote(friendID: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(1775097840, friendID, note);
}

/**
 * StartQuickLogin 用第三方快捷登录（provider: kungal / hikarinagi）登录 YukiHub 账号。
 * 
 * 打开浏览器 → 等本地回调 → code 交给自建后端换 YukiHub 会话。
 * 与手机版行为一致：成功后即进入登录态（含心跳），云同步开关保持原样。
 */
export function StartQuickLogin(provider: string): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(1991868436, provider).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SyncAccountNow 立刻与云端同步一次游戏库。
 * 
 * 上传方向复用 YukiHubExporter（产出的就是 Android 侧 schema 5 快照，
 * 与手机版 `/sync/upload` 收的格式完全相同）；下载方向复用 YukiHubImporter。
 */
export function SyncAccountNow(): $CancellablePromise<vo$0.AccountSyncResult> {
    return $Call.ByID(2194510418).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * TestAccountConnection 探测账号服务是否可达（邮箱界面上的「测试连接」）。
 */
export function TestAccountConnection(): $CancellablePromise<void> {
    return $Call.ByID(3337605335);
}

/**
 * UpdateAccountNickname 修改云端昵称。
 */
export function UpdateAccountNickname(nickname: string): $CancellablePromise<void> {
    return $Call.ByID(2698353080, nickname);
}

/**
 * UploadChatImage 上传聊天图片字节，返回可直接放进消息 content 的 URL。
 */
export function UploadChatImage(data: string, mimeType: string): $CancellablePromise<string> {
    return $Call.ByID(5905520, data, mimeType);
}

// Private type creation functions
const $$createType0 = vo$0.AccountLevel.createFrom;
const $$createType1 = vo$0.AccountStatus.createFrom;
const $$createType2 = yukihubaccount$0.ChatMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = yukihubaccount$0.UserProfile.createFrom;
const $$createType5 = yukihubaccount$0.ChatEmoji.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = yukihubaccount$0.ChatGroup.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = vo$0.ChatStickerList.createFrom;
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = yukihubaccount$0.FriendRequests.createFrom;
const $$createType12 = yukihubaccount$0.FriendList.createFrom;
const $$createType13 = yukihubaccount$0.Friend.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = vo$0.ChatImagePick.createFrom;
const $$createType16 = vo$0.AccountSyncResult.createFrom;
