// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as processutils$0 from "../utils/processutils/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddGameFromWebMetadata 用于接收前端/导入流程中的完整刮削结果（含 tags）并一次性入库。
 */
export function AddGameFromWebMetadata(meta: vo$0.GameMetadataFromWebVO): $CancellablePromise<void> {
    return $Call.ByID(3188808793, meta);
}

/**
 * BatchSetGameHidden 批量设置「已隐藏」标记，返回实际改到的条数。
 * 
 * 走单条 UPDATE 而不是前端循环调 SetGameHidden：一次调用只抢一次 DuckDB
 * 写锁（全选可能几百条），也不会出现「部分成功」被前端误报成全部失败。
 * 返回的 count 小于请求条数说明有些 id 已不存在，调用方应据此提示。
 */
export function BatchSetGameHidden(ids: string[], hidden: boolean): $CancellablePromise<number> {
    return $Call.ByID(2709273571, ids, hidden);
}

/**
 * BatchUpdateStatus 批量更新多个游戏的游玩状态
 */
export function BatchUpdateStatus(ids: string[], status: string): $CancellablePromise<void> {
    return $Call.ByID(1939642532, ids, status);
}

/**
 * ClearGameArt 清除自定义图：先删受管目录里的文件，再清空列（对齐手机端 clearArt）。
 */
export function ClearGameArt(gameID: string, kind: string): $CancellablePromise<void> {
    return $Call.ByID(1048445941, gameID, kind);
}

export function DeleteGame(id: string): $CancellablePromise<void> {
    return $Call.ByID(2461646920, id);
}

export function DeleteGameMetadataSource(gameID: string, source: enums$0.SourceType): $CancellablePromise<void> {
    return $Call.ByID(3048937664, gameID, source);
}

export function DeleteGames(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(896113889, ids);
}

/**
 * DetectCompatTools 扫描常见位置，返回找到的 Locale Emulator / Magpie 路径。
 */
export function DetectCompatTools(): $CancellablePromise<$models.CompatToolsDetection> {
    return $Call.ByID(6866639).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DownloadCoverImage 下载远程封面图片并替换为本地托管路径。
 */
export function DownloadCoverImage(gameID: string, coverURL: string): $CancellablePromise<string> {
    return $Call.ByID(2705768161, gameID, coverURL);
}

/**
 * EnrichLegacyGameMetadataSourceIDs fills missing Bangumi, VNDB, Steam, and Hikarinagi
 * metadata sources for games whose default source is one of those providers.
 */
export function EnrichLegacyGameMetadataSourceIDs(): $CancellablePromise<$models.GameIDEnrichmentResult> {
    return $Call.ByID(1823305825).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportCoverImage opens a save dialog and copies the game's cover image to the selected location.
 */
export function ExportCoverImage(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(3086126831, gameID);
}

/**
 * ExportLaunchShortcut exports a per-game .url shortcut that re-enters YukiHub via protocol.
 */
export function ExportLaunchShortcut(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(3666205118, gameID);
}

export function FetchMetadata(req: vo$0.MetadataRequest): $CancellablePromise<models$0.Game> {
    return $Call.ByID(2732404318, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function FetchMetadataByName(name: string): $CancellablePromise<vo$0.GameMetadataFromWebVO[]> {
    return $Call.ByID(3303674484, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function FetchMetadataFromWeb(req: vo$0.MetadataRequest): $CancellablePromise<vo$0.GameMetadataFromWebVO> {
    return $Call.ByID(728716540, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FindGameGuideDocuments 递归查找游戏目录中的说明文档。
 */
export function FindGameGuideDocuments(gameID: string): $CancellablePromise<vo$0.GameGuideDocument[]> {
    return $Call.ByID(4183576222, gameID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetGameByID(id: string): $CancellablePromise<models$0.Game> {
    return $Call.ByID(3154479601, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGameMetadataSources(gameID: string): $CancellablePromise<models$0.GameMetadataSource[]> {
    return $Call.ByID(2877647658, gameID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetGameScreenshots 返回游戏库详情（右侧详情面板 / 完整详情页）「媒体」小节要用的截图地址。
 * 
 * 合并规则逐字对齐手机端 BigScreenMeta：按来源优先级取**第一个非空来源**的整组截图
 * （不跨来源拼接），上限 8 张 —— 各来源解析时已各自截到 2 张（见 metadata 包）。
 * 数据直接读 game_metadata_sources.cache_json（沿用手机版 VnMetadata 结构，含
 * screenshotUrls），所以两端看到的是同一组图。没有任何来源带截图时返回空切片，
 * 前端把整块截图区收起来。
 */
export function GetGameScreenshots(gameID: string): $CancellablePromise<string[]> {
    return $Call.ByID(2334470654, gameID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetGames(req: vo$0.GameListRequest): $CancellablePromise<vo$0.GameListResponse> {
    return $Call.ByID(2074870666, req).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetRunningProcesses 获取系统中正在运行的进程列表（过滤掉系统进程）
 */
export function GetRunningProcesses(): $CancellablePromise<processutils$0.ProcessInfo[]> {
    return $Call.ByID(1124921291).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * OpenGameGuideDocument 使用系统默认应用打开指定的游戏说明文档。
 */
export function OpenGameGuideDocument(gameID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(2538227664, gameID, relativePath);
}

/**
 * OpenLocalPath 打开指定的本地文件或目录（通过资源管理器）
 */
export function OpenLocalPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(958861979, path);
}

/**
 * PreviewLegacyGameMetadataSourceIDs calculates the same changes as enrichment
 * without modifying the user's library.
 */
export function PreviewLegacyGameMetadataSourceIDs(): $CancellablePromise<$models.GameIDEnrichmentPreview> {
    return $Call.ByID(928219716).then(($result: any) => {
        return $$createType13($result);
    });
}

export function RefreshAllGamesMetadata(): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(2761252055).then(($result: any) => {
        return $$createType14($result);
    });
}

export function RefreshAllGamesMetadataWithFields(fields: enums$0.MetadataUpdateField[]): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(3625736150, fields).then(($result: any) => {
        return $$createType14($result);
    });
}

export function RefreshGamesMetadata(gameIDs: string[]): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(700545834, gameIDs).then(($result: any) => {
        return $$createType14($result);
    });
}

export function RefreshGamesMetadataWithFields(gameIDs: string[], fields: enums$0.MetadataUpdateField[]): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(1297801843, gameIDs, fields).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * RemoveGameTrailer 清除游戏的预告片：先删受管目录里的文件，再清空列。
 */
export function RemoveGameTrailer(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(922065006, gameID);
}

/**
 * ResolveExecutablePathForImport 解析导入时的可执行路径：
 * - 如果是可执行文件路径，直接返回
 * - 如果是目录，弹出文件选择器让用户手动选择可执行文件
 */
export function ResolveExecutablePathForImport(path: string): $CancellablePromise<string> {
    return $Call.ByID(2735323202, path);
}

/**
 * SaveCoverImageDataURL 保存前端剪贴板读取到的图片 data URL。
 */
export function SaveCoverImageDataURL(gameID: string, dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(2974093025, gameID, dataURL);
}

/**
 * SelectCoverImage 选择封面图片并保存到 covers 目录
 */
export function SelectCoverImage(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(132776213, gameID);
}

/**
 * SelectCoverImageWithTempID 选择封面图片并使用临时ID保存（用于新增游戏时）
 */
export function SelectCoverImageWithTempID(): $CancellablePromise<string> {
    return $Call.ByID(3880830030);
}

/**
 * SelectGameArt 选择并保存大屏自定义标题图 / 背景图（对齐手机版 M10 logo_path/bg_path）。
 * kind 取 mediautils.GameArtKindLogo / GameArtKindBg，返回写入库的 /local/bigscreen/art/... 地址。
 * 流程对齐手机端 onArtPicked：先复制新文件成功，再删旧文件，最后落列，任一步失败旧图都还在。
 */
export function SelectGameArt(gameID: string, kind: string, currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2995269956, gameID, kind, currentPath);
}

export function SelectGameDirectory(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(456843702, currentPath);
}

export function SelectGameExecutable(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(1188050431, currentPath);
}

/**
 * SelectGameTrailer 弹出视频文件选择器，把用户选中的本地视频复制进受管目录并写入游戏。
 * 返回 /local/trailers/... 地址供大屏与设置面板使用；用户取消时返回空串且不报错。
 */
export function SelectGameTrailer(gameID: string, currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(129985758, gameID, currentPath);
}

/**
 * SelectSaveDirectory 选择存档目录
 */
export function SelectSaveDirectory(rootPath: string): $CancellablePromise<string> {
    return $Call.ByID(317927955, rootPath);
}

/**
 * SelectSaveFile 选择存档文件
 */
export function SelectSaveFile(rootPath: string): $CancellablePromise<string> {
    return $Call.ByID(2408812998, rootPath);
}

export function SelectWineRunnerExecutable(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2559326662, currentPath);
}

export function SetDefaultMetadataSource(gameID: string, source: enums$0.SourceType): $CancellablePromise<void> {
    return $Call.ByID(3919185436, gameID, source);
}

/**
 * SetGameHidden 单独更新「已隐藏」标记。
 * 
 * 语义对齐手机版 GameRepository.setHidden：只改 hidden 与 updated_at，
 * 不碰封面 / PV / 时长等其他字段 —— 走 UpdateGame 那种整行覆盖会把
 * 详情页手上可能已经过期的字段一起写回去。
 * 
 * updated_at 必须推进：云同步按「对端 updated_at 不早于本地」判断谁更新，
 * 隐藏状态变了却不更新时间戳，手机端就永远收不到这次隐藏。
 */
export function SetGameHidden(gameID: string, hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(736556997, gameID, hidden);
}

/**
 * StartRemoteCoverImageDownloadTask queues a download-management task for all games
 * whose current cover URL still points to a remote image.
 */
export function StartRemoteCoverImageDownloadTask(): $CancellablePromise<string> {
    return $Call.ByID(1410543464);
}

export function UpdateGame(game: models$0.Game): $CancellablePromise<void> {
    return $Call.ByID(4009221246, game);
}

/**
 * UpdateGameFromRemote 从远程数据源更新游戏信息
 */
export function UpdateGameFromRemote(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(2263524144, gameID);
}

/**
 * UpdateGameFromRemoteBySource refreshes a game from one explicitly linked provider.
 */
export function UpdateGameFromRemoteBySource(gameID: string, source: enums$0.SourceType): $CancellablePromise<void> {
    return $Call.ByID(3528197024, gameID, source);
}

/**
 * UpdateGameFromRemoteWithFields 从远程数据源更新指定字段。
 */
export function UpdateGameFromRemoteWithFields(gameID: string, fields: enums$0.MetadataUpdateField[]): $CancellablePromise<void> {
    return $Call.ByID(2367644949, gameID, fields);
}

/**
 * UpdateGameProcessName 更新游戏的进程名
 * 当用户选择了实际的游戏进程时调用
 */
export function UpdateGameProcessName(gameID: string, processName: string): $CancellablePromise<void> {
    return $Call.ByID(1705920312, gameID, processName);
}

export function UpsertGameMetadataSource(gameID: string, source: enums$0.SourceType, sourceID: string): $CancellablePromise<void> {
    return $Call.ByID(3925881704, gameID, source, sourceID);
}

// Private type creation functions
const $$createType0 = $models.CompatToolsDetection.createFrom;
const $$createType1 = $models.GameIDEnrichmentResult.createFrom;
const $$createType2 = models$0.Game.createFrom;
const $$createType3 = vo$0.GameMetadataFromWebVO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = vo$0.GameGuideDocument.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = models$0.GameMetadataSource.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = vo$0.GameListResponse.createFrom;
const $$createType11 = processutils$0.ProcessInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.GameIDEnrichmentPreview.createFrom;
const $$createType14 = vo$0.MetadataRefreshResult.createFrom;
