// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BatchImportGamesToSteam(gameIDs: string[]): $CancellablePromise<$models.SteamBatchImportResult> {
    return $Call.ByID(297544880, gameIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetGameCompatibilityTools 返回指定游戏可用的 Wine/Proton 快捷工具。
 */
export function GetGameCompatibilityTools(gameID: string): $CancellablePromise<$models.GameCompatibilityToolsInfo> {
    return $Call.ByID(2329531978, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetGameSteamCompatibility(gameID: string): $CancellablePromise<$models.SteamCompatibilityInfo> {
    return $Call.ByID(830408929, gameID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGameSteamStatus(gameID: string): $CancellablePromise<$models.SteamLaunchStatus> {
    return $Call.ByID(596984333, gameID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetLocalProtonTools(): $CancellablePromise<$models.LocalProtonTool[]> {
    return $Call.ByID(2824450473).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ImportGameToSteam(gameID: string): $CancellablePromise<$models.SteamImportResult> {
    return $Call.ByID(3268789273, gameID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * OpenGameCompatibilityTool 打开指定游戏的 Wine/Proton 快捷工具。
 */
export function OpenGameCompatibilityTool(gameID: string, action: string): $CancellablePromise<string> {
    return $Call.ByID(1083713867, gameID, action);
}

export function OpenGameSteamProtonPrefix(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(960698933, gameID);
}

export function RestartSteamClient(): $CancellablePromise<void> {
    return $Call.ByID(140996259);
}

export function SetGameSteamCompatibilityTool(gameID: string, toolName: string): $CancellablePromise<$models.SteamCompatibilityInfo> {
    return $Call.ByID(3484874087, gameID, toolName).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetGameSteamLaunchOptions(gameID: string, launchOptions: string): $CancellablePromise<$models.SteamLaunchStatus> {
    return $Call.ByID(1395297278, gameID, launchOptions).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SteamBatchImportResult.createFrom;
const $$createType1 = $models.GameCompatibilityToolsInfo.createFrom;
const $$createType2 = $models.SteamCompatibilityInfo.createFrom;
const $$createType3 = $models.SteamLaunchStatus.createFrom;
const $$createType4 = $models.LocalProtonTool.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.SteamImportResult.createFrom;
