// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

/**
 * CompatToolsDetection 是自动检测到的转区 / 超分工具路径。
 * 
 * YukiHub 自带一份 Locale Emulator 与 Magpie（放在程序目录的 compat-tools\ 下，
 * 见该目录的 SOURCE.txt），所以正常情况下用户什么都不用配；
 * 检测同时覆盖「系统里已经装过」「用户自己换了新版本」两种情况。
 */
export class CompatToolsDetection {
    "localeEmulatorPath": string;
    "magpiePath": string;

    /**
     * PortableToolsDir 是「把工具丢进这里就能被认出来」的目录，供设置界面提示。
     */
    "portableToolsDir": string;

    /** Creates a new CompatToolsDetection instance. */
    constructor($$source: Partial<CompatToolsDetection> = {}) {
        if (!("localeEmulatorPath" in $$source)) {
            this["localeEmulatorPath"] = "";
        }
        if (!("magpiePath" in $$source)) {
            this["magpiePath"] = "";
        }
        if (!("portableToolsDir" in $$source)) {
            this["portableToolsDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompatToolsDetection instance from a string or object.
     */
    static createFrom($$source: any = {}): CompatToolsDetection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompatToolsDetection($$parsedSource as Partial<CompatToolsDetection>);
    }
}

export class CoverImageDownloadItem {
    "GameID": string;
    "GameName": string;
    "CoverURL": string;

    /** Creates a new CoverImageDownloadItem instance. */
    constructor($$source: Partial<CoverImageDownloadItem> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = "";
        }
        if (!("GameName" in $$source)) {
            this["GameName"] = "";
        }
        if (!("CoverURL" in $$source)) {
            this["CoverURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverImageDownloadItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CoverImageDownloadItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoverImageDownloadItem($$parsedSource as Partial<CoverImageDownloadItem>);
    }
}

/**
 * DownloadStatus 下载状态
 */
export enum DownloadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadStatusPending = "pending",
    DownloadStatusDownloading = "downloading",
    DownloadStatusExtracting = "extracting",
    DownloadStatusPaused = "paused",
    DownloadStatusDone = "done",
    DownloadStatusError = "error",
    DownloadStatusCancelled = "cancelled",
};

/**
 * DownloadTask 单个下载任务
 */
export class DownloadTask {
    "id": string;
    "request": vo$0.InstallRequest;
    "status": DownloadStatus;
    "created_at"?: string | null;

    /**
     * 0~100
     */
    "progress": number;

    /**
     * bytes downloaded
     */
    "downloaded": number;

    /**
     * bytes total (0 = unknown)
     */
    "total": number;
    "error"?: string;

    /**
     * 下载完成后的本地路径
     */
    "file_path"?: string;

    /** Creates a new DownloadTask instance. */
    constructor($$source: Partial<DownloadTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("request" in $$source)) {
            this["request"] = (new vo$0.InstallRequest());
        }
        if (!("status" in $$source)) {
            this["status"] = DownloadStatus.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadTask instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadTask {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField1_0($$parsedSource["request"]);
        }
        return new DownloadTask($$parsedSource as Partial<DownloadTask>);
    }
}

/**
 * FriendPlayEvent 是一条「好友开始玩游戏」的通知内容。
 * 
 * 前端拿它渲染 Steam 风格卡片（头像 + 「昵称 正在玩 / 绿色游戏名」）。
 * 
 * 昵称做成数组是为了「同一游戏多人同时开始」能合成一条通知，只有一个好友时
 * 长度为 1。（注意：这不是照着某张截图的推论，而是为了不刷屏 —— 一次弹出
 * 三四条同一个游戏的卡片没有意义。）
 */
export class FriendPlayEvent {
    "uids": number[];
    "nicknames": string[];
    "avatars"?: string[];
    "game_title": string;

    /**
     * Seq 是通知序号，由 OverlayService 分配。通知浮层「挂载时拉一次 +
     * 订阅事件」两条路都会拿到同一条，靠它去重。
     */
    "seq"?: number;

    /** Creates a new FriendPlayEvent instance. */
    constructor($$source: Partial<FriendPlayEvent> = {}) {
        if (!("uids" in $$source)) {
            this["uids"] = [];
        }
        if (!("nicknames" in $$source)) {
            this["nicknames"] = [];
        }
        if (!("game_title" in $$source)) {
            this["game_title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FriendPlayEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FriendPlayEvent {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uids" in $$parsedSource) {
            $$parsedSource["uids"] = $$createField0_0($$parsedSource["uids"]);
        }
        if ("nicknames" in $$parsedSource) {
            $$parsedSource["nicknames"] = $$createField1_0($$parsedSource["nicknames"]);
        }
        if ("avatars" in $$parsedSource) {
            $$parsedSource["avatars"] = $$createField2_0($$parsedSource["avatars"]);
        }
        return new FriendPlayEvent($$parsedSource as Partial<FriendPlayEvent>);
    }
}

/**
 * GameCompatibilityToolsInfo 描述某个游戏可用的 Wine/Proton 快捷工具。
 */
export class GameCompatibilityToolsInfo {
    "supported": boolean;
    "runner_kind": string;
    "prefix_path": string;
    "drive_c_path": string;
    "app_id": string;
    "winetricks_path": string;
    "winetricks_source": string;
    "winetricks_available": boolean;
    "winetricks_error": string;
    "protontricks_path": string;
    "protontricks_source": string;
    "protontricks_available": boolean;
    "protontricks_error": string;
    "actions": string[];
    "message": string;

    /** Creates a new GameCompatibilityToolsInfo instance. */
    constructor($$source: Partial<GameCompatibilityToolsInfo> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("runner_kind" in $$source)) {
            this["runner_kind"] = "";
        }
        if (!("prefix_path" in $$source)) {
            this["prefix_path"] = "";
        }
        if (!("drive_c_path" in $$source)) {
            this["drive_c_path"] = "";
        }
        if (!("app_id" in $$source)) {
            this["app_id"] = "";
        }
        if (!("winetricks_path" in $$source)) {
            this["winetricks_path"] = "";
        }
        if (!("winetricks_source" in $$source)) {
            this["winetricks_source"] = "";
        }
        if (!("winetricks_available" in $$source)) {
            this["winetricks_available"] = false;
        }
        if (!("winetricks_error" in $$source)) {
            this["winetricks_error"] = "";
        }
        if (!("protontricks_path" in $$source)) {
            this["protontricks_path"] = "";
        }
        if (!("protontricks_source" in $$source)) {
            this["protontricks_source"] = "";
        }
        if (!("protontricks_available" in $$source)) {
            this["protontricks_available"] = false;
        }
        if (!("protontricks_error" in $$source)) {
            this["protontricks_error"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameCompatibilityToolsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GameCompatibilityToolsInfo {
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField13_0($$parsedSource["actions"]);
        }
        return new GameCompatibilityToolsInfo($$parsedSource as Partial<GameCompatibilityToolsInfo>);
    }
}

export class GameIDEnrichmentPreview {
    "scanned_games": number;
    "enrichable_games": number;
    "unchanged_games": number;
    "added_sources": number;
    "items": GameIDEnrichmentPreviewItem[];

    /** Creates a new GameIDEnrichmentPreview instance. */
    constructor($$source: Partial<GameIDEnrichmentPreview> = {}) {
        if (!("scanned_games" in $$source)) {
            this["scanned_games"] = 0;
        }
        if (!("enrichable_games" in $$source)) {
            this["enrichable_games"] = 0;
        }
        if (!("unchanged_games" in $$source)) {
            this["unchanged_games"] = 0;
        }
        if (!("added_sources" in $$source)) {
            this["added_sources"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameIDEnrichmentPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): GameIDEnrichmentPreview {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField4_0($$parsedSource["items"]);
        }
        return new GameIDEnrichmentPreview($$parsedSource as Partial<GameIDEnrichmentPreview>);
    }
}

export class GameIDEnrichmentPreviewItem {
    "game_id": string;
    "game_name": string;
    "default_source": enums$0.SourceType;
    "default_source_id": string;
    "existing_sources": GameIDEnrichmentSource[];
    "added_sources": GameIDEnrichmentSource[];
    "can_enrich": boolean;
    "reason": string;

    /** Creates a new GameIDEnrichmentPreviewItem instance. */
    constructor($$source: Partial<GameIDEnrichmentPreviewItem> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("default_source" in $$source)) {
            this["default_source"] = enums$0.SourceType.$zero;
        }
        if (!("default_source_id" in $$source)) {
            this["default_source_id"] = "";
        }
        if (!("existing_sources" in $$source)) {
            this["existing_sources"] = [];
        }
        if (!("added_sources" in $$source)) {
            this["added_sources"] = [];
        }
        if (!("can_enrich" in $$source)) {
            this["can_enrich"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameIDEnrichmentPreviewItem instance from a string or object.
     */
    static createFrom($$source: any = {}): GameIDEnrichmentPreviewItem {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("existing_sources" in $$parsedSource) {
            $$parsedSource["existing_sources"] = $$createField4_0($$parsedSource["existing_sources"]);
        }
        if ("added_sources" in $$parsedSource) {
            $$parsedSource["added_sources"] = $$createField5_0($$parsedSource["added_sources"]);
        }
        return new GameIDEnrichmentPreviewItem($$parsedSource as Partial<GameIDEnrichmentPreviewItem>);
    }
}

/**
 * GameIDEnrichmentResult summarizes one library-wide ID enrichment operation.
 */
export class GameIDEnrichmentResult {
    "scanned_games": number;
    "matched_games": number;
    "updated_games": number;
    "added_sources": number;
    "unmatched_games": number;
    "skipped_games": number;

    /** Creates a new GameIDEnrichmentResult instance. */
    constructor($$source: Partial<GameIDEnrichmentResult> = {}) {
        if (!("scanned_games" in $$source)) {
            this["scanned_games"] = 0;
        }
        if (!("matched_games" in $$source)) {
            this["matched_games"] = 0;
        }
        if (!("updated_games" in $$source)) {
            this["updated_games"] = 0;
        }
        if (!("added_sources" in $$source)) {
            this["added_sources"] = 0;
        }
        if (!("unmatched_games" in $$source)) {
            this["unmatched_games"] = 0;
        }
        if (!("skipped_games" in $$source)) {
            this["skipped_games"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameIDEnrichmentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameIDEnrichmentResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameIDEnrichmentResult($$parsedSource as Partial<GameIDEnrichmentResult>);
    }
}

export class GameIDEnrichmentSource {
    "source_type": enums$0.SourceType;
    "source_id": string;

    /** Creates a new GameIDEnrichmentSource instance. */
    constructor($$source: Partial<GameIDEnrichmentSource> = {}) {
        if (!("source_type" in $$source)) {
            this["source_type"] = enums$0.SourceType.$zero;
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameIDEnrichmentSource instance from a string or object.
     */
    static createFrom($$source: any = {}): GameIDEnrichmentSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameIDEnrichmentSource($$parsedSource as Partial<GameIDEnrichmentSource>);
    }
}

export class GameLibraryPathChangeItem {
    "record_type": string;
    "record_id": string;
    "record_name": string;
    "field": string;
    "old_path": string;
    "new_path": string;
    "target_exists": boolean;
    "steam_managed": boolean;

    /** Creates a new GameLibraryPathChangeItem instance. */
    constructor($$source: Partial<GameLibraryPathChangeItem> = {}) {
        if (!("record_type" in $$source)) {
            this["record_type"] = "";
        }
        if (!("record_id" in $$source)) {
            this["record_id"] = "";
        }
        if (!("record_name" in $$source)) {
            this["record_name"] = "";
        }
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("old_path" in $$source)) {
            this["old_path"] = "";
        }
        if (!("new_path" in $$source)) {
            this["new_path"] = "";
        }
        if (!("target_exists" in $$source)) {
            this["target_exists"] = false;
        }
        if (!("steam_managed" in $$source)) {
            this["steam_managed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLibraryPathChangeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLibraryPathChangeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameLibraryPathChangeItem($$parsedSource as Partial<GameLibraryPathChangeItem>);
    }
}

export class GameLibraryPathChangePreview {
    "old_configured_path": string;
    "new_configured_path": string;
    "old_library_path": string;
    "new_library_path": string;
    "changes": GameLibraryPathChangeItem[];
    "affected_game_count": number;
    "affected_download_task_count": number;
    "missing_target_count": number;
    "steam_game_count": number;
    "blocking_download_task_count": number;

    /** Creates a new GameLibraryPathChangePreview instance. */
    constructor($$source: Partial<GameLibraryPathChangePreview> = {}) {
        if (!("old_configured_path" in $$source)) {
            this["old_configured_path"] = "";
        }
        if (!("new_configured_path" in $$source)) {
            this["new_configured_path"] = "";
        }
        if (!("old_library_path" in $$source)) {
            this["old_library_path"] = "";
        }
        if (!("new_library_path" in $$source)) {
            this["new_library_path"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("affected_game_count" in $$source)) {
            this["affected_game_count"] = 0;
        }
        if (!("affected_download_task_count" in $$source)) {
            this["affected_download_task_count"] = 0;
        }
        if (!("missing_target_count" in $$source)) {
            this["missing_target_count"] = 0;
        }
        if (!("steam_game_count" in $$source)) {
            this["steam_game_count"] = 0;
        }
        if (!("blocking_download_task_count" in $$source)) {
            this["blocking_download_task_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLibraryPathChangePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLibraryPathChangePreview {
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField4_0($$parsedSource["changes"]);
        }
        return new GameLibraryPathChangePreview($$parsedSource as Partial<GameLibraryPathChangePreview>);
    }
}

export class GameLibraryPathChangeResult {
    "new_configured_path": string;
    "updated_game_count": number;
    "updated_download_task_count": number;

    /** Creates a new GameLibraryPathChangeResult instance. */
    constructor($$source: Partial<GameLibraryPathChangeResult> = {}) {
        if (!("new_configured_path" in $$source)) {
            this["new_configured_path"] = "";
        }
        if (!("updated_game_count" in $$source)) {
            this["updated_game_count"] = 0;
        }
        if (!("updated_download_task_count" in $$source)) {
            this["updated_download_task_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLibraryPathChangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLibraryPathChangeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameLibraryPathChangeResult($$parsedSource as Partial<GameLibraryPathChangeResult>);
    }
}

/**
 * ImportResult 导入结果
 */
export class ImportResult {
    /**
     * 成功导入数量
     */
    "success": number;

    /**
     * 跳过数量（已存在）
     */
    "skipped": number;

    /**
     * 失败数量
     */
    "failed": number;

    /**
     * 失败的游戏名称
     */
    "failed_names": string[];

    /**
     * 跳过的游戏名称
     */
    "skipped_names": string[];

    /**
     * 导入的游玩记录数量
     */
    "sessions_imported": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("failed_names" in $$source)) {
            this["failed_names"] = [];
        }
        if (!("skipped_names" in $$source)) {
            this["skipped_names"] = [];
        }
        if (!("sessions_imported" in $$source)) {
            this["sessions_imported"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failed_names" in $$parsedSource) {
            $$parsedSource["failed_names"] = $$createField3_0($$parsedSource["failed_names"]);
        }
        if ("skipped_names" in $$parsedSource) {
            $$parsedSource["skipped_names"] = $$createField4_0($$parsedSource["skipped_names"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

export class LibraryDirectorySelection {
    "directory": string;
    "initial_directory_invalid": boolean;

    /** Creates a new LibraryDirectorySelection instance. */
    constructor($$source: Partial<LibraryDirectorySelection> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("initial_directory_invalid" in $$source)) {
            this["initial_directory_invalid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryDirectorySelection instance from a string or object.
     */
    static createFrom($$source: any = {}): LibraryDirectorySelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryDirectorySelection($$parsedSource as Partial<LibraryDirectorySelection>);
    }
}

export class LocalProtonTool {
    "id": string;
    "name": string;
    "display_name": string;
    "path": string;
    "proton_path": string;
    "source": string;
    "built_in": boolean;

    /** Creates a new LocalProtonTool instance. */
    constructor($$source: Partial<LocalProtonTool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("proton_path" in $$source)) {
            this["proton_path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("built_in" in $$source)) {
            this["built_in"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalProtonTool instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalProtonTool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalProtonTool($$parsedSource as Partial<LocalProtonTool>);
    }
}

/**
 * PortableProtocolStatus describes the current yukihub:// scheme binding.
 */
export class PortableProtocolStatus {
    "registered": boolean;
    "registeredPath": string;
    "currentPath": string;
    "upToDate": boolean;

    /** Creates a new PortableProtocolStatus instance. */
    constructor($$source: Partial<PortableProtocolStatus> = {}) {
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("registeredPath" in $$source)) {
            this["registeredPath"] = "";
        }
        if (!("currentPath" in $$source)) {
            this["currentPath"] = "";
        }
        if (!("upToDate" in $$source)) {
            this["upToDate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortableProtocolStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PortableProtocolStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortableProtocolStatus($$parsedSource as Partial<PortableProtocolStatus>);
    }
}

/**
 * PortableSetupStatus is the aggregate snapshot consumed by the settings UI.
 */
export class PortableSetupStatus {
    "buildMode": string;
    "isPortable": boolean;
    "platform": string;
    "executablePath": string;
    "protocol": PortableProtocolStatus;

    /** Creates a new PortableSetupStatus instance. */
    constructor($$source: Partial<PortableSetupStatus> = {}) {
        if (!("buildMode" in $$source)) {
            this["buildMode"] = "";
        }
        if (!("isPortable" in $$source)) {
            this["isPortable"] = false;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("executablePath" in $$source)) {
            this["executablePath"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = (new PortableProtocolStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortableSetupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PortableSetupStatus {
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("protocol" in $$parsedSource) {
            $$parsedSource["protocol"] = $$createField4_0($$parsedSource["protocol"]);
        }
        return new PortableSetupStatus($$parsedSource as Partial<PortableSetupStatus>);
    }
}

/**
 * PreviewGame 预览导入的游戏信息
 */
export class PreviewGame {
    "name": string;
    "developer": string;
    "source_type": string;
    "source_id": string;
    "path": string;
    "exists": boolean;
    "conflict_type": string;
    "existing_id": string;
    "existing_name": string;
    "add_time": string;
    "has_path": boolean;

    /** Creates a new PreviewGame instance. */
    constructor($$source: Partial<PreviewGame> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("developer" in $$source)) {
            this["developer"] = "";
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = "";
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("conflict_type" in $$source)) {
            this["conflict_type"] = "";
        }
        if (!("existing_id" in $$source)) {
            this["existing_id"] = "";
        }
        if (!("existing_name" in $$source)) {
            this["existing_name"] = "";
        }
        if (!("add_time" in $$source)) {
            this["add_time"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("has_path" in $$source)) {
            this["has_path"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewGame instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewGame($$parsedSource as Partial<PreviewGame>);
    }
}

/**
 * StartupFailure contains the diagnostic message shown when YukiHub cannot
 * create its main window.
 */
export class StartupFailure {
    "message": string;

    /** Creates a new StartupFailure instance. */
    constructor($$source: Partial<StartupFailure> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupFailure($$parsedSource as Partial<StartupFailure>);
    }
}

export class SteamBatchImportItemResult {
    "game_id": string;
    "status": SteamLaunchStatus;
    "imported": boolean;
    "error"?: string;

    /** Creates a new SteamBatchImportItemResult instance. */
    constructor($$source: Partial<SteamBatchImportItemResult> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new SteamLaunchStatus());
        }
        if (!("imported" in $$source)) {
            this["imported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamBatchImportItemResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamBatchImportItemResult {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        return new SteamBatchImportItemResult($$parsedSource as Partial<SteamBatchImportItemResult>);
    }
}

export class SteamBatchImportResult {
    "items": SteamBatchImportItemResult[];
    "imported_count": number;
    "existing_count": number;
    "failed_count": number;
    "backup_path": string;

    /** Creates a new SteamBatchImportResult instance. */
    constructor($$source: Partial<SteamBatchImportResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("imported_count" in $$source)) {
            this["imported_count"] = 0;
        }
        if (!("existing_count" in $$source)) {
            this["existing_count"] = 0;
        }
        if (!("failed_count" in $$source)) {
            this["failed_count"] = 0;
        }
        if (!("backup_path" in $$source)) {
            this["backup_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamBatchImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamBatchImportResult {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SteamBatchImportResult($$parsedSource as Partial<SteamBatchImportResult>);
    }
}

export class SteamCompatibilityInfo {
    "supported": boolean;
    "steam_installed": boolean;
    "steam_root": string;
    "app_id": string;
    "proton_prefix": string;
    "current_tool": string;
    "default_tool": string;
    "tools": SteamCompatibilityTool[];

    /** Creates a new SteamCompatibilityInfo instance. */
    constructor($$source: Partial<SteamCompatibilityInfo> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("steam_installed" in $$source)) {
            this["steam_installed"] = false;
        }
        if (!("steam_root" in $$source)) {
            this["steam_root"] = "";
        }
        if (!("app_id" in $$source)) {
            this["app_id"] = "";
        }
        if (!("proton_prefix" in $$source)) {
            this["proton_prefix"] = "";
        }
        if (!("current_tool" in $$source)) {
            this["current_tool"] = "";
        }
        if (!("default_tool" in $$source)) {
            this["default_tool"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamCompatibilityInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamCompatibilityInfo {
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField7_0($$parsedSource["tools"]);
        }
        return new SteamCompatibilityInfo($$parsedSource as Partial<SteamCompatibilityInfo>);
    }
}

export class SteamCompatibilityTool {
    "name": string;
    "display_name": string;
    "path": string;
    "built_in": boolean;

    /** Creates a new SteamCompatibilityTool instance. */
    constructor($$source: Partial<SteamCompatibilityTool> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("built_in" in $$source)) {
            this["built_in"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamCompatibilityTool instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamCompatibilityTool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamCompatibilityTool($$parsedSource as Partial<SteamCompatibilityTool>);
    }
}

export class SteamImportResult {
    "status": SteamLaunchStatus;
    "imported": boolean;
    "backup_path": string;

    /** Creates a new SteamImportResult instance. */
    constructor($$source: Partial<SteamImportResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new SteamLaunchStatus());
        }
        if (!("imported" in $$source)) {
            this["imported"] = false;
        }
        if (!("backup_path" in $$source)) {
            this["backup_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamImportResult {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new SteamImportResult($$parsedSource as Partial<SteamImportResult>);
    }
}

export class SteamLaunchStatus {
    "state": string;
    "ready": boolean;
    "steam_installed": boolean;
    "steam_running": boolean;
    "launch_id": string;
    "launch_kind": string;
    "user_id": string;
    "proton_prefix": string;

    /** Creates a new SteamLaunchStatus instance. */
    constructor($$source: Partial<SteamLaunchStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("steam_installed" in $$source)) {
            this["steam_installed"] = false;
        }
        if (!("steam_running" in $$source)) {
            this["steam_running"] = false;
        }
        if (!("launch_id" in $$source)) {
            this["launch_id"] = "";
        }
        if (!("launch_kind" in $$source)) {
            this["launch_kind"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("proton_prefix" in $$source)) {
            this["proton_prefix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamLaunchStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamLaunchStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamLaunchStatus($$parsedSource as Partial<SteamLaunchStatus>);
    }
}

export class UpdateApplyResult {
    "started": boolean;
    "fallback_used": boolean;
    "file_count": number;

    /** Creates a new UpdateApplyResult instance. */
    constructor($$source: Partial<UpdateApplyResult> = {}) {
        if (!("started" in $$source)) {
            this["started"] = false;
        }
        if (!("fallback_used" in $$source)) {
            this["fallback_used"] = false;
        }
        if (!("file_count" in $$source)) {
            this["file_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateApplyResult($$parsedSource as Partial<UpdateApplyResult>);
    }
}

/**
 * UpdateCheckResult 更新检查结果
 */
export class UpdateCheckResult {
    /**
     * 是否有更新
     */
    "has_update": boolean;

    /**
     * 当前版本
     */
    "current_ver": string;

    /**
     * 最新版本
     */
    "latest_ver": string;

    /**
     * 发布日期
     */
    "release_date": string;

    /**
     * 更新日志内容
     */
    "changelog": string[];

    /**
     * 下载链接
     */
    "downloads": { [_ in string]?: string };

    /**
     * 发布页地址
     */
    "release_url": string;

    /**
     * 应用内更新清单
     */
    "update_manifest_url": string;

    /**
     * 本次实际生效的更新源：gitcode / github / custom
     */
    "update_source": string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("current_ver" in $$source)) {
            this["current_ver"] = "";
        }
        if (!("latest_ver" in $$source)) {
            this["latest_ver"] = "";
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("changelog" in $$source)) {
            this["changelog"] = [];
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = {};
        }
        if (!("release_url" in $$source)) {
            this["release_url"] = "";
        }
        if (!("update_manifest_url" in $$source)) {
            this["update_manifest_url"] = "";
        }
        if (!("update_source" in $$source)) {
            this["update_source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField4_0($$parsedSource["changelog"]);
        }
        if ("downloads" in $$parsedSource) {
            $$parsedSource["downloads"] = $$createField5_0($$parsedSource["downloads"]);
        }
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = vo$0.InstallRequest.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = GameIDEnrichmentPreviewItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GameIDEnrichmentSource.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GameLibraryPathChangeItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = PortableProtocolStatus.createFrom;
const $$createType10 = SteamLaunchStatus.createFrom;
const $$createType11 = SteamBatchImportItemResult.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = SteamCompatibilityTool.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Map($Create.Any, $Create.Any);
